CREATE TABLE CREATEDATE(
	T_ID VARCHAR2(1000) NOT NULL,
	U_ID VARCHAR2(1000) NOT NULL,
	STARTDATE DATE NOT NULL, 
	ENDDATE DATE NOT NULL
);

SELECT * FROM CREATEDATE;

SELECT (ENDDATE - STARTDATE) FROM CREATEDATE;

DROP TABLE CREATEDATE;
